import { Component } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent {
  title:string="Travelling";
  text:string="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae suscipit tellus mauris a diam maecenas sed enim. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Odio ut sem nulla pharetra diam sit amet. Magna fermentum iaculis eu non diam. Varius quam quisque id diam. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. In fermentum posuere urna nec tincidunt praesent. At in tellus integer feugiat scelerisque. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Amet volutpat consequat mauris nunc congue. Luctus accumsan tortor posuere ac ut consequat semper viverra. Rhoncus urna neque viverra justo. Sodales ut etiam sit amet nisl purus. Volutpat odio facilisis mauris sit amet massa vitae. Cursus euismod quis viverra nibh cras pulvinar mattis. A erat nam at lectus. Et sollicitudin ac orci phasellus egestas. Ornare lectus sit amet est placerat in. Tortor id aliquet lectus proin nibh nisl. Donec et odio pellentesque diam volutpat commodo. Proin sagittis nisl rhoncus mattis. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Dui id ornare arcu odio ut sem nulla pharetra diam. Quis imperdiet massa tincidunt nunc pulvinar. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Blandit turpis cursus in hac. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Aliquam etiam erat velit scelerisque in dictum non consectetur. Quam elementum pulvinar etiam non. Scelerisque eleifend donec pretium vulputate sapien nec sagittis. Egestas integer eget aliquet nibh praesent tristique magna. Vestibulum mattis ullamcorper velit sed. Venenatis cras sed felis eget velit aliquet sagittis id consectetur. Arcu felis bibendum ut tristique et egestas. Ac ut consequat semper viverra nam libero justo. Justo donec enim diam vulputate ut pharetra sit amet aliquam. Arcu risus quis varius quam quisque. At consectetur lorem donec massa sapien faucibus et molestie ac. Volutpat odio facilisis mauris sit amet. Lorem ipsum dolor sit amet consectetur. Vitae suscipit tellus mauris a diam maecenas sed enim. Nisl pretium fusce id velit ut tortor.";
  image_beach:string="./assets/images/beach.png";
}
